version: "3.3"
services:
  nats:
    image: nats-streaming:0.19-alpine
    ports:
      - 4222:4222
      - 8222:8222
  ###StartBlock(deps)
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_DB: triton
      POSTGRES_PASSWORD: yeAUemR82sK82jcNjR0E8BqYejUUYtLM
    ports:
      - 5432:5432
  ###EndBlock(deps)
