// Code generated by entc, DO NOT EDIT.

package media

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the media type in the database.
	Label = "media"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldSourceURI holds the string denoting the source_uri field in the database.
	FieldSourceURI = "source_uri"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusPercent holds the string denoting the status_percent field in the database.
	FieldStatusPercent = "status_percent"

	// Table holds the table name of the media in the database.
	Table = "media"
)

// Columns holds all SQL columns for media fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldType,
	FieldSource,
	FieldSourceURI,
	FieldStatus,
	FieldStatusPercent,
}

var (
	// DefaultStatus holds the default value on creation for the status field.
	DefaultStatus string
	// DefaultStatusPercent holds the default value on creation for the status_percent field.
	DefaultStatusPercent float32
	// DefaultID holds the default value on creation for the id field.
	DefaultID func() uuid.UUID
)
